Switch to Micrometer 1.10.0-SNAPSHOT version (#2315)
- Fix exception when generating reference documentation.

Jun 22, 2022 10:52:13 AM io.micrometer.docs.metrics.MetricSearchingFileVisitor visitFile
SEVERE: Failed to parse file [/.../reactor-netty/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java] due to an error
java.lang.IllegalStateException: There's no nested type with name [Http2ConnectionProviderMeters.Http2ConnectionProviderMetersTags]
        at io.micrometer.docs.commons.ParsingUtils.lambda$keyValueEntries$1(ParsingUtils.java:79)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.micrometer.docs.commons.ParsingUtils.lambda$keyValueEntries$2(ParsingUtils.java:78)
        at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4966)
        at io.micrometer.docs.commons.ParsingUtils.keyValueEntries(ParsingUtils.java:75)
        at io.micrometer.docs.metrics.MetricSearchingFileVisitor.parseMetric(MetricSearchingFileVisitor.java:170)
        at io.micrometer.docs.metrics.MetricSearchingFileVisitor.visitFile(MetricSearchingFileVisitor.java:86)
        at io.micrometer.docs.metrics.MetricSearchingFileVisitor.visitFile(MetricSearchingFileVisitor.java:50)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at io.micrometer.docs.metrics.DocsFromSources.generate(DocsFromSources.java:62)
        at io.micrometer.docs.metrics.DocsFromSources.main(DocsFromSources.java:53)

- Adapt to the changes in TimerObservationHandler and SampleTestRunner
- For the time being we don't need LongTaskTimer