Use URI when creating Path object from a classloader resource
 URL#getFile returns on Windows the path in the form
 "/C:/<path-to-the-resource>" this causes tests failures

 reactor.ipc.netty.http.client.HttpClientTest > secureSendFile FAILED
    java.nio.file.InvalidPathException: Illegal char <:> at index 2:
        /C:/<path-to-the-resource>
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at reactor.ipc.netty.http.client.HttpClientTest.secureSendFile
        (HttpClientTest.java:624)