[test] Update to windows-2022 for GraalVM smoke tests
On windows-2019 the tests are failing with

```
Error: On Windows, GraalVM Native Image for JDK 17 requires Visual Studio 2022 version 17.1.0 or later (C/C++ Optimizing Compiler Version 19.31 or later).
```