Ensure all cases, when Http2FrameCodec is not available, are handled properly
Ensure PooledRef is invalidated in the cases when a stream cannot be opened.

java.lang.NullPointerException: Cannot invoke "io.netty.handler.codec.http2.Http2FrameCodec.connection()" because "frameCodec" is null
	at reactor.netty.http.client.Http2ConnectionProvider$DisposableAcquire.operationComplete(Http2ConnectionProvider.java:320)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

Related to https://github.com/reactor/reactor-netty/issues/2031#issuecomment-1062685557