Add root cause exception when throwing PrematureCloseException (#2937)
Reactor Netty’s HttpClient relies on Netty’s Http2FrameCodecBuilder. This codec, by default, enforces the MAX_HEADER_LIST_SIZE found in the SETTINGS sent by the server, meaning that If a request’s header list size exceeds the SETTINGS MAX_HEADER_LIST_SIZE limit, then HpackEncoder throws a HeaderListSizeException. Consequently, the request is not sent, and the client receives a PrematureCloseException error without any details.

Let's just add more specific root cause to the PrematureCloseException in order to make it meaningful in the case the request header size exceeds MAX_HEADER_LIST_SIZE (or if whatever Netty Http2 Codec exceptions are caught while writing the request out).

Example:

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
Caused by: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (1024)

Fixes #2927